version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: products_db
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: products_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - products_network

  redis:
    image: redis:7-alpine
    container_name: products_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - products_network

  app:
    build: .
    container_name: products_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: products_db
      DB_USER: products_user
      DB_PASSWORD: products_password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    depends_on:
      - postgres
    networks:
      - products_network

volumes:
  postgres_data:
  redis_data:

networks:
  products_network:
    driver: bridge 